### PR TITLE
NavigationCommand lambda with receiver

### PR DESCRIPTION
**Pull request by Volatile-Memory**
simplify callsites by using a lambda with receiver in NavigationCommand

### CODE REVIEW

**Comment by Volatile-Memory** [comment]
@Zhuinden any thoughts?

**Comment by Zhuinden** [comment]
I was thinking about this one, on second read it's a good idea, but I'm not sure if it'll actually make the intent of the code clearer to understand for those who see it for the first time.

**Comment by Volatile-Memory** [comment]
I think people will still need to look at examples or the documentation to know how to use this either way.

I think the approach you had is nice in that people who know how to ask for the IDE to autocomplete a lambda with parameter names filled in would automatically see everything, but they could still get the gist by looking at a kdoc @sample or by looking at other callsites.

In all the places your sample calls this lambda, the context is not used which i think will be the majority case for most apps so things are quite short and elegant with the receiver syntax.

**Comment by Zhuinden** [comment]
Sold, thank you for the contribution :+1:

**Pull request merged**
